---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld
spec:
  ports:
    - port: 3000
  selector:
    name: noejs-helloworld

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-helloworld
  annotations:
    flux.weave.works/automated: "false"
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        name: nodejs-helloworld
    spec:
      containers:
      - name: nodejs-helloworld
        image: eu.gcr.io/parcel-vision/nodejs-helloworld:1.3
        ports:
        - containerPort: 3000
